function items = upstreams()
%UPSTREAMS Return upstream metadata for the nirs4all aggregate binding.

items = struct( ...
    'key', {'dag_ml', 'dag_ml_data', 'formats', 'io', 'datasets', 'methods'}, ...
    'package', {'dag-ml-wasm', 'dag-ml-data-wasm', 'nirs4all-formats-wasm', 'nirs4all-io-wasm', 'nirs4all-datasets-wasm', '@nirs4all/methods-wasm'}, ...
    'role', { ...
        'Leakage-safe DAG/ML execution coordinator', ...
        'Sample-aligned data contracts for DAG/ML runtimes', ...
        'Spectroscopy/NIRS vendor file readers', ...
        'Dataset assembly bridge', ...
        'DOI-pinned NIRS dataset catalog', ...
        'Portable C ABI PLS/NIRS numerical engine' ...
    } ...
);
end
